spring.application.name=it_to_do
# Configuração da URL de conexão (JDBC)
spring.datasource.url=jdbc:mariadb://localhost:3306/nome_do_banco?createDatabaseIfNotExist=true
spring.datasource.username=antony
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Define como o Hibernate gerencia as tabelas no banco de dados:
# 'update' atualiza a estrutura do banco automaticamente conforme as entidades Java
spring.jpa.hibernate.ddl-auto=update

# Opcional: exibe os comandos SQL executados no console (útil para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
